lt=/data/data/com.termux/files/home/lingti
wj=/data/data/com.termux/files/home/unbounded
fg=/data/data/com.termux/files/home/forge
dj=/data/data/com.termux/files/home/dingjie
lu=/data/data/com.termux/files/home/lu
kk=/data/data/com.termux/files/home/kuai
wang=/data/data/com.termux/files/home/zhiwang
sms=/data/data/com.termux/files/home/sms
